### ISSUE TITLE
M1 arm64 error: `qemu: uncaught target signal 11 (Segmentation fault) - core dumped`

### ISSUE THREAD

**Issue by v-sh** [pap/devcontainer-elixir-phoenix#14]
Hi! 👋 I was trying to use this container on the M1 mac, and run into an error.

This is what I get if I just try to run `mix` on my project:

```
Base version: 20210213-f94866e
Running as user vscode
miVS code server 1.77.3
x
Docker server 20.10.20 | client 20.10.2
Docker-Compose 1.28.0

Phoenix Devcontainer version: 20210705-262bfd9

qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Elixir:   
OTP:      
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Phoenix:  

Terminal Docker tools aliases:
 * alpine: launch an interactive alpine 3.11 container
 * dive: inspect the layers of a Docker image
 * ld: run lazydocker in a container
[WARN] - (starship::utils): Executing command "elixir" timed out.                                                              
[WARN] - (starship::utils): You can set command_timeout in your config to a higher value to allow longer-running commands to keep executing.

workspace🔒 on  main [?] is 📦 v0.1.0 via 💧                                                                       31d15h ◒  
❯ mix
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[1]    1936 segmentation fault  mix
```

Some googling led me to https://github.com/docker/for-mac/issues/6204 which says:

> Please encourage the author of this container to supply an arm64 or multi-arch image, not just an Intel one. Now that M1 is a mainstream platform, we think that most container authors will be keen to do this.
> 
> Creating intel images on M1 Macs is not guaranteed to work, can you to build this on an intel or a CI machine?

As I see in https://hub.docker.com/r/papereira/devcontainer-elixir-phoenix/tags these are all `amd64`, can you please push multi-arch image? I don't know much about it myself, but the first link from google looks sane: https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/ 

I'll be happy to help, if you need more information/testing! 💚 

cc @pap

**Comment by pap** [comment]
Took me too long to reply to this one @v-sh :(
I have made some changes and pushed `linux/arm64` and `linux/amd64` images into the docker registry.
